### ISSUE TITLE
default game-directory not default

### ISSUE THREAD

**Issue by greener-dot-ca** [ezfe/minecraft-jar-command#2]
I have to specify `--game-directory ~/Library/Application\ Support/minecraft` to get the default behaviour despite what it says in `README.md`. Any chance this is broken, or am I doing something wrong?

**Comment by ezfe** [comment]
Hmm - that seems to be my bad, looks like I never changed the default behavior. The default is in fact a temporary directory. I'll change the README for now and try to get a new version out at some point since I did want that to default to the actual folder.

**Comment by ezfe** [comment]
All set, I just released a new version that defaults to the right directory
