### ISSUE TITLE
[Request] support for Fabric loader / custom jars

### ISSUE THREAD

**Issue by cadenkriese** [ezfe/minecraft-jar-command#3]
I'm not sure how difficult this would be to implement, but I'd love to be able to run my standard Minecraft setup with fabric mods natively (or as native as you can get with Java).

**Comment by ezfe** [comment]
Hi @fl0gic,

This should be possible but it depends how much changes with Fabric. If the libraries used are the same then this shouldn't be an issue. Unfortunately right now the system expects to find the full and complete version in [the manifest](https://f001.backblazeb2.com/file/com-ezekielelin-publicFiles/lwjgl-arm/version_manifest_v2.json). I've never used Fabric so I don't know how much changes.

When I have time to work on this, I'm planning on fixing support for running local versions that aren't in the manifest. I need to change the order-of-operations for getting version information a little bit, that's all.

**Comment by cadenkriese** [comment]
Just checking up on this, does the completion of https://github.com/LWJGL/lwjgl3/issues/601 have any positive impacts on this issue or this project as a whole?

**Comment by ezfe** [comment]
@cadenkriese Thanks for letting me know about that - at very least I'll be able to bring the profile far more in-line with the default one, which may be sufficient to have it work in any application. I'll investigate doing this when I have time (maybe today or this weekend).

**Comment by ezfe** [comment]
@cadenkriese I forgot to followup here. The profiles I'm generating are compatible with the official launcher, so any modding approach should be the same. It does require patching the JAR file, which I'm working on improving.

I don't have the time to investigate additional modding, but someone else can look into that.
