### ISSUE TITLE
Microsoft account compatibility

### ISSUE THREAD

**Issue by Fall2299** [ezfe/minecraft-jar-command#5]
Hi, does this enable me to use my Microsoft account to run MC natively? Or do I need a Mojang-account?

Kind regards

**Comment by ezfe** [comment]
Hi @Fall2299, my account has not been migrated so I cannot test it. I don't know how the new authentication works, so at this time it's Mojang-account only. If you can find resources for how to login with Microsoft accounts I can try to incorporate them.

**Comment by Fall2299** [comment]
Thanks for the reply, all I know is that the two factor Microsoft authentication was implemented by a couple of other launchers. Thusfar I have not found a way to launch MC natively using a Microsoft account.

**Comment by ezfe** [comment]
@Fall2299 Could you link to another launcher and I might be able to figure out how they did it

**Comment by Fall2299** [comment]
ATLauncher supports Microsoft accounts since December 16 2020. I have already contacted their developer but not yet received a solution.

**Comment by Fall2299** [comment]
I dont know why but I seem unable to link them

https://atlauncher.com/

found a more detailed issue 

https://github.com/ATLauncher/ATLauncher/issues/415

**Comment by ezfe** [comment]
Looking through the steps required, I don't feel comfortable attempting this until my account is migrated - sorry!

If you own Minecraft, you can edit the source code for this project to remove the authentication checks. The authentication happens here:

https://github.com/ezfe/minecraft-jar-command/blob/main/Sources/minecraft-jar-command/Commands/RunCommand.swift#L80

You would want to change the `auth` variable to be assigned to a fake `AuthResult()` object like this: `AuthResult(accessToken: "", clientToken: "", profile: Profile(name: "", id: ""))`

**Comment by Fall2299** [comment]
No worries, I totally understand! Thanks for the help! I’ll keep trying and update if it works

**Comment by ezfe** [comment]
@Fall2299 ive added this in on https://github.com/ezfe/m1craft
