### ISSUE TITLE
Stucked in the download of "Asset Collection"

### ISSUE THREAD

**Issue by MoustacheOff** [ezfe/minecraft-jar-command#6]
Is it normal that i'm stucked here ?

`Last login: Fri Mar 12 07:29:48 on console
user@Mac-mini ~ % minecraft-jar-command
Queued up downloads
==== Starting Download Batch : Libraries ====
==== Starting Download Batch : Asset Collection ====

`
Thank you for your attention

**Comment by ezfe** [comment]
This phase can take a long time - you can look in Activity Monitor; expect it to download a couple hundred MB.

<img width="1551" alt="Screen Shot 2021-03-12 at 2 15 57 PM" src="https://user-images.githubusercontent.com/1449259/110987698-78ed6680-833d-11eb-9c84-fd92bd62c055.png">

**Comment by ezfe** [comment]
If your program is no longer downloading anything (see in the chart the rightmost blue section) please let me know and I can release a build with more logging.

**Comment by MoustacheOff** [comment]
Thank you very much for your reply! I left the download on for a day and nothing happened but now I'm going to watch the download carefully.
I'll let you know if I still can't...

Have a nice day!

**Comment by MoustacheOff** [comment]
It has now been 2 days since the download and I sometimes have no data downloaded. The average speed is 2 kb/s.

**Comment by MoustacheOff** [comment]
Right now i'm at 17,33 GBs

**Comment by ezfe** [comment]
Hi @MoustacheOff - I'm going to add more logging and release a new version - It will include slightly more detail in the output of the program.

**Comment by ezfe** [comment]
Hi @MoustacheOff 

Can you run `brew upgrade minecraft-jar-command` (it should install version 2.3.2) then try again? When you run it again, what is the messages shown? I added one indicating when it finishes, since I want to verify that it is or isn't completing the download process.

**Comment by MoustacheOff** [comment]
user@Mac-mini ~ % brew upgrade minecraft-jar-command
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (ezfe/tap and homebrew/core).
==> New Formulae
as-tree                    libunwind                  pyqt-networkauth
cluster-api                lttng-ust                  threemux
glibc                      numactl                    virtualenv
haskell-language-server    obfs4proxy                 zlib-ng
iconsur                    pyqt-3d
kertish-dfs                pyqt-builder
==> Updated Formulae
Updated 521 formulae.
==> Renamed Formulae
kde-extra-cmake-modules -> extra-cmake-modules
kde-karchive -> karchive
kde-kdoctools -> kdoctools
kde-ki18n -> ki18n
kde-threadweaver -> threadweaver
minizip2 -> minizip-ng
pyqt5 -> pyqt@5

==> Upgrading 1 outdated package:
ezfe/tap/minecraft-jar-command v2.2.0 -> v2.3.2
==> Upgrading ezfe/tap/minecraft-jar-command v2.2.0 -> v2.3.2 
==> Downloading https://github.com/ezfe/minecraft-jar-command/archive/v2.3.2.ta
==> Downloading from https://codeload.github.com/ezfe/minecraft-jar-command/tar
######################################################################## 100.0%
==> swift build --disable-sandbox -c release
🍺  /opt/homebrew/Cellar/minecraft-jar-command/v2.3.2: 5 files, 4.2MB, built in 36 seconds
Removing: /opt/homebrew/Cellar/minecraft-jar-command/v2.2.0... (5 files, 4.2MB)
user@Mac-mini ~ % minecraft-jar-command
Queued up downloads
==== Starting Download Batch : Libraries ====
==== Starting Download Batch : Asset Collection ====

**Comment by MoustacheOff** [comment]
**Update** : ==== Finished Download Batch : Libraries ====

**Comment by ezfe** [comment]
How fast is your internet connection, If you go to https://fast.com what does it show?

**Comment by MoustacheOff** [comment]
I've got 14 Mb/s

**Comment by MoustacheOff** [comment]
Right now I'm stucked at ==== Finished Download Batch : Libraries ====

**Comment by MoustacheOff** [comment]
Same now

**Comment by ezfe** [comment]
Hi - I'm sorry that I haven't followed up again, I've been busy. I don't really have any idea what's going on. Your internet seems fast enough so I'm not sure where the problem is.

Unfortunately I don't have the time/ability to help you here, I'm sorry. If you would like to download and run from source in Xcode you might be able to figure out more – and I'm happy to answer code questions if you choose to do that.

Sorry!
