### ISSUE TITLE
Issue with 1.17

### ISSUE THREAD

**Issue by nathandaven** [ezfe/minecraft-jar-command#7]
Hey, playing 1.16 works just fine but getting this error when running the provided command from readme:

`keyNotFound(CodingKeys(stringValue: "downloads", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"downloads\", intValue: nil) (\"downloads\").", underlyingError: nil))
Error: decodingError("The data couldn’t be read because it is missing.")`

**Comment by ezfe** [comment]
Hmm - I’m on vacation unfortunately but you could set it up manually in the regular launcher https://gist.github.com/ezfe/965f8f2b2d60931615a251d4b786df4c

**Comment by ezfe** [comment]
@nathandaven Does it work now? I have an update with better logic that doesn't require the special arguments in the works but hopefully that fixed it.
